In [ ]:
!pip install -q langchain langchain-community langchain-groq langchain-text-splitters chromadb sentence-transformers pypdf deepeval

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 64.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 65.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.5/349.5 kB 27.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 57.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.2/668.2 kB 34.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 49.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 55.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 51.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.9/395.9 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 3.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-adk 2.3.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.43.0 which is incompatible.
google-adk 2.3.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.43.0 which is incompatible.

In [ ]:
from google.colab import userdata
import os
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")  # set this once in Colab's Secrets panel (key icon, left sidebar)
PDF_PATH = "mpr_april_2025.pdf"  # match your uploaded filename exactly

In [ ]:
from google.colab import files
uploaded = files.upload()  # select mpr_april_2025.pdf when prompted

import os
print(os.listdir())
print("Exists:", os.path.exists(PDF_PATH))

Saving mpr_april_2025.pdf to mpr_april_2025 (1).pdf
['.config', 'mpr_april_2025 (1).pdf', 'mpr_april_2025.pdf', 'sample_data']
Exists: True

In [ ]:
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

docs = PyPDFLoader(PDF_PATH).load()
chunks = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=300).split_documents(docs)
print(f"{len(docs)} pages, {len(chunks)} chunks")

/tmp/ipykernel_1081/3656135642.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

116 pages, 461 chunks

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectordb = Chroma.from_documents(chunks, embeddings)
print("Vector store ready")

/tmp/ipykernel_1081/2512416694.py:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Vector store ready

In [ ]:
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
retriever = vectordb.as_retriever(search_kwargs={"k": 4})
prompt = ChatPromptTemplate.from_template(
    "Use ONLY this context to answer. If not found, say so.\n\n"
    "Context:\n{context}\n\nQuestion: {question}\n\nAnswer:"
)

def ask(question):
    docs = retriever.invoke(question)
    context = "\n\n".join(d.page_content for d in docs)
    messages = prompt.format_messages(context=context, question=question)
    response = llm.invoke(messages)
    return response.content, docs

print("RAG function ready")

RAG function ready

In [ ]:
answer, docs = ask("What was the repo rate as of April 2025?")
print(answer)
for d in docs:
    print("Page:", d.metadata.get("page") + 1)

6.25 per cent.
Page: 18
Page: 76
Page: 12
Page: 97

In [ ]:
from sentence_transformers import CrossEncoder
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def retrieve_and_rerank(query, initial_k=15, final_k=4):
    candidates = vectordb.similarity_search(query, k=initial_k)
    pairs = [[query, doc.page_content] for doc in candidates]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(candidates, scores), key=lambda x: x[1], reverse=True)
    return [doc for doc, score in ranked[:final_k]]

print("Re-ranker ready")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Re-ranker ready

In [ ]:
import pandas as pd

eval_data = [
    {"question": "What was India's real GDP growth for 2024-25 per the second advance estimate?",
     "expected_answer_summary": "Real GDP growth was estimated at 6.5% year-on-year, with real GVA growth at 6.4%.",
     "ground_truth_page": 11},

    {"question": "By how much was the Cash Reserve Ratio (CRR) reduced in December 2024?",
     "expected_answer_summary": "The CRR was reduced by 50 basis points in December 2024.",
     "ground_truth_page": 12},

    {"question": "What did the MPC decide at its February 2025 meeting?",
     "expected_answer_summary": "The MPC unanimously voted to reduce the policy repo rate by 25 basis points to 6.25% and continued with the neutral stance.",
     "ground_truth_page": 13},

    {"question": "What model is used in Box I.1 to study inflation expectations of economic agents?",
     "expected_answer_summary": "A vector error correction model (VECM) is used to explore the relationship between key indicators and inflation expectations.",
     "ground_truth_page": 16},

    {"question": "What did professional forecasters project for CPI inflation in Q4:2024-25 as per the March 2025 survey?",
     "expected_answer_summary": "CPI inflation was projected to decline from 5.6% in Q3:2024-25 to 3.9% in Q4.",
     "ground_truth_page": 17},

    {"question": "What is the CPI inflation projection for 2025-26?",
     "expected_answer_summary": "CPI inflation is projected to average 4.0% in 2025-26, with Q1 at 3.6%, Q2 at 3.9%, Q3 at 3.8%, and Q4 at 4.4%.",
     "ground_truth_page": 18},

    {"question": "What is the real GDP growth projection for 2025-26?",
     "expected_answer_summary": "Real GDP growth is expected at 6.5% in 2025-26, with Q1 at 6.5%, Q2 at 6.7%, Q3 at 6.6%, and Q4 at 6.3%.",
     "ground_truth_page": 20},

    {"question": "Where did headline CPI inflation stand relative to the target by February 2025?",
     "expected_answer_summary": "Headline inflation declined below the target rate of 4% by February 2025.",
     "ground_truth_page": 25},

    {"question": "How much did headline inflation surge from August to September 2024?",
     "expected_answer_summary": "Headline inflation surged by 1.8 percentage points, from 3.7% in August to 5.5% in September 2024.",
     "ground_truth_page": 26},

    {"question": "What was food inflation in February 2025?",
     "expected_answer_summary": "Food inflation softened to 3.8% by February 2025.",
     "ground_truth_page": 31},

    {"question": "How did cereals inflation move from October 2024 to February 2025?",
     "expected_answer_summary": "Cereals inflation moderated from 6.9% in October 2024 to 6.1% in February 2025.",
     "ground_truth_page": 32},

    {"question": "What mainly drove the pick-up in core inflation between August 2024 and February 2025?",
     "expected_answer_summary": "The pick-up was largely contributed by the personal care and effects sub-group, reflecting a spike in gold and silver prices.",
     "ground_truth_page": 40},

    {"question": "What was PFCE growth in Q3:2024-25 and its contribution to GDP growth?",
     "expected_answer_summary": "Private final consumption expenditure grew 6.9% in Q3:2024-25, contributing 4.1 percentage points to overall GDP growth.",
     "ground_truth_page": 48},

    {"question": "How much did domestic air passenger traffic grow in Q3:2024-25?",
     "expected_answer_summary": "Domestic air passenger traffic rose by 11.4% in Q3:2024-25.",
     "ground_truth_page": 49},

    {"question": "What was India's investment rate in 2023-24?",
     "expected_answer_summary": "The investment rate was 31.4% of GDP in 2023-24, moderating from 32.6% the previous year.",
     "ground_truth_page": 52},

    {"question": "What were the Centre's gross market borrowings in 2024-25?",
     "expected_answer_summary": "The Centre's gross market borrowings amounted to ₹14.01 lakh crore in 2024-25.",
     "ground_truth_page": 57},

    {"question": "What was foodgrains production per the second advance estimate for 2024-25?",
     "expected_answer_summary": "Foodgrains production was estimated at 3,309.2 lakh tonnes, an increase of 4.8% over the previous year.",
     "ground_truth_page": 61},

    {"question": "What was rice procurement as of March 31, 2025?",
     "expected_answer_summary": "Rice procurement reached 511.5 lakh tonnes, an increase of 6.9% over the previous year.",
     "ground_truth_page": 62},

    {"question": "How did industrial sector growth move in 2024-25 per the second advance estimate?",
     "expected_answer_summary": "Industrial sector growth moderated to 4.3% in 2024-25, from 11.0% in the previous year.",
     "ground_truth_page": 63},

    {"question": "What were the major drivers of liquidity during H2:2024-25?",
     "expected_answer_summary": "Changes in Government of India cash balances, expansion in currency in circulation, and volatile capital flows were the major drivers.",
     "ground_truth_page": 70},

    {"question": "What was the average daily net absorption under the LAF in Q3:2024-25?",
     "expected_answer_summary": "Average daily net absorption under the LAF (including MSF) declined to ₹0.8 lakh crore in Q3:2024-25, from ₹1.3 lakh crore in the preceding quarter.",
     "ground_truth_page": 71},

    {"question": "What was Reserve Money (RM) growth as of March 28, 2025?",
     "expected_answer_summary": "Reserve money expanded by 3.3% year-on-year as on March 28, 2025, compared to 6.7% a year ago.",
     "ground_truth_page": 73},

    {"question": "What range did the 10-year G-sec yield move in during H2:2024-25?",
     "expected_answer_summary": "The 10-year G-sec yield moved in the range of 6.62% to 6.86% during H2:2024-25.",
     "ground_truth_page": 78},

    {"question": "What was the weighted average maturity of outstanding G-secs at end-March 2025?",
     "expected_answer_summary": "The weighted average maturity increased to 13.24 years at end-March 2025, from 12.96 years at end-September 2024.",
     "ground_truth_page": 80},

    {"question": "How much did credit to MSMEs grow in February 2025?",
     "expected_answer_summary": "Credit to MSMEs grew by 12.3% in February 2025.",
     "ground_truth_page": 89},

    {"question": "By how much did the 1-year median MCLR rise during the May 2022 to January 2025 tightening cycle?",
     "expected_answer_summary": "The 1-year median MCLR of scheduled commercial banks increased by 178 basis points, in response to the cumulative 250 bps repo rate hike.",
     "ground_truth_page": 93},

    {"question": "How did Euro area and UK GDP growth compare in Q4:2024?",
     "expected_answer_summary": "Euro area GDP growth moderated to 0.9% (q-o-q, saar) while the UK economy grew by 0.4% (q-o-q, saar) in Q4:2024.",
     "ground_truth_page": 100},

    {"question": "How did Brazil's GDP growth move in Q4:2024?",
     "expected_answer_summary": "Brazil's GDP growth moderated to 3.6% year-on-year in Q4:2024, from 4.1% in Q3.",
     "ground_truth_page": 101},

    {"question": "What milestone did gold prices cross in Q1:2025?",
     "expected_answer_summary": "Gold prices surpassed USD 3,100 per ounce for the first time, gaining 19.5% quarter-on-quarter.",
     "ground_truth_page": 105},

    {"question": "How did Russia's CPI inflation move between September 2024 and February 2025?",
     "expected_answer_summary": "Russia's CPI inflation accelerated from 8.6% in September 2024 to 10.1% in February 2025.",
     "ground_truth_page": 106},
]

eval_df = pd.DataFrame(eval_data)
print(f"{len(eval_df)} eval questions ready, unique pages: {eval_df['ground_truth_page'].nunique()}")
eval_df.head()

30 eval questions ready, unique pages: 30

,question,expected_answer_summary,ground_truth_page
0,What was India's real GDP growth for 2024-25 p...,Real GDP growth was estimated at 6.5% year-on-...,11
1,By how much was the Cash Reserve Ratio (CRR) r...,The CRR was reduced by 50 basis points in Dece...,12
2,What did the MPC decide at its February 2025 m...,The MPC unanimously voted to reduce the policy...,13
3,What model is used in Box I.1 to study inflati...,A vector error correction model (VECM) is used...,16
4,What did professional forecasters project for ...,CPI inflation was projected to decline from 5....,17

In [ ]:
def retrieval_metrics(retriever, eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    details = []
    for _, row in eval_df.iterrows():
        docs = retriever.invoke(row["question"])
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
            status = f"HIT (rank {rank})"
        else:
            reciprocal_ranks.append(0.0)
            status = "MISS"
        details.append({"question": row["question"], "ground_truth_page": gt_page,
                         "retrieved_pages": pages, "status": status})
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr, pd.DataFrame(details)

hit_rate, mrr, details_df = retrieval_metrics(retriever, eval_df, k=4)
print(f"Hit-rate@4: {hit_rate:.2%}")
print(f"MRR: {mrr:.3f}")
pd.set_option("display.max_colwidth", 60)
details_df

Hit-rate@4: 83.33%
MRR: 0.656

,question,ground_truth_page,retrieved_pages,status
0,What was India's real GDP growth for 2024-25 per the sec...,11,"[12, 48, 11, 59]",HIT (rank 3)
1,By how much was the Cash Reserve Ratio (CRR) reduced in ...,12,"[12, 73, 69, 107]",HIT (rank 1)
2,What did the MPC decide at its February 2025 meeting?,13,"[12, 12, 13, 13]",HIT (rank 3)
3,What model is used in Box I.1 to study inflation expecta...,16,"[5, 16, 28, 16]",HIT (rank 2)
4,What did professional forecasters project for CPI inflat...,17,"[18, 17, 25, 26]",HIT (rank 2)
5,What is the CPI inflation projection for 2025-26?,18,"[26, 31, 27, 12]",MISS
6,What is the real GDP growth projection for 2025-26?,20,"[20, 48, 21, 20]",HIT (rank 1)
7,Where did headline CPI inflation stand relative to the t...,25,"[25, 105, 105, 26]",HIT (rank 1)
8,How much did headline inflation surge from August to Sep...,26,"[26, 25, 41, 105]",HIT (rank 1)
9,What was food inflation in February 2025?,31,"[31, 25, 31, 30]",HIT (rank 1)
10,How did cereals inflation move from October 2024 to Febr...,32,"[32, 33, 25, 31]",HIT (rank 1)
11,What mainly drove the pick-up in core inflation between ...,40,"[41, 40, 39, 105]",HIT (rank 2)
12,What was PFCE growth in Q3:2024-25 and its contribution ...,48,"[100, 100, 53, 50]",MISS
13,How much did domestic air passenger traffic grow in Q3:2...,49,"[66, 67, 48, 49]",HIT (rank 4)
14,What was India's investment rate in 2023-24?,52,"[59, 87, 84, 59]",MISS
15,What were the Centre's gross market borrowings in 2024-25?,57,"[57, 57, 54, 82]",HIT (rank 1)
16,What was foodgrains production per the second advance es...,61,"[61, 61, 35, 31]",HIT (rank 1)
17,"What was rice procurement as of March 31, 2025?",62,"[33, 62, 62, 35]",HIT (rank 2)
18,How did industrial sector growth move in 2024-25 per the...,63,"[100, 12, 99, 101]",MISS
19,What were the major drivers of liquidity during H2:2024-25?,70,"[69, 70, 75, 43]",HIT (rank 2)
20,What was the average daily net absorption under the LAF ...,71,"[70, 69, 59, 71]",HIT (rank 4)
21,"What was Reserve Money (RM) growth as of March 28, 2025?",73,"[73, 12, 60, 73]",HIT (rank 1)
22,What range did the 10-year G-sec yield move in during H2...,78,"[78, 80, 79, 113]",HIT (rank 1)
23,What was the weighted average maturity of outstanding G-...,80,"[80, 80, 76, 18]",HIT (rank 1)
24,How much did credit to MSMEs grow in February 2025?,89,"[89, 89, 88, 92]",HIT (rank 1)
25,By how much did the 1-year median MCLR rise during the M...,93,"[99, 101, 39, 99]",MISS
26,How did Euro area and UK GDP growth compare in Q4:2024?,100,"[100, 100, 47, 48]",HIT (rank 1)
27,How did Brazil's GDP growth move in Q4:2024?,101,"[101, 48, 12, 13]",HIT (rank 1)
28,What milestone did gold prices cross in Q1:2025?,105,"[105, 104, 11, 103]",HIT (rank 1)
29,How did Russia's CPI inflation move between September 20...,106,"[106, 105, 105, 39]",HIT (rank 1)

In [ ]:
def reranked_retrieval_metrics(eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    for _, row in eval_df.iterrows():
        docs = retrieve_and_rerank(row["question"], initial_k=15, final_k=k)
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
        else:
            reciprocal_ranks.append(0.0)
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr

hit_rate_rerank, mrr_rerank = reranked_retrieval_metrics(eval_df, k=4)
print(f"Hit-rate@4 (with re-ranker): {hit_rate_rerank:.2%}")
print(f"MRR (with re-ranker): {mrr_rerank:.3f}")

Hit-rate@4 (with re-ranker): 90.00%
MRR (with re-ranker): 0.828

In [ ]:
!pip install -q rank_bm25

In [ ]:
from langchain_community.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(chunks)
bm25_retriever.k = 4
print("BM25 retriever ready")

BM25 retriever ready

In [ ]:
docs = bm25_retriever.invoke("What was the repo rate as of April 2025?")
for d in docs:
    print("Page:", d.metadata.get("page") + 1)
    print(d.page_content[:200])
    print("---")

Page: 16
6
Monetary Policy Report April 2025
Box I.1: What Affects Inflation Expectations of Economic Agents?
Anchoring inflation expectations is paramount in
monetary policy formulation, particularly in an i
---
Page: 75
During H2:2024-25, the WACR, which remained
within the policy corridor and hovered close to the
policy repo rate during October-November, hardened,
moving close to and occasionally breaching the ce
---
Page: 69
and USD/INR Buy/Sell swaps. The Reserve Bank
increased the aggregate limit available to Standalone
Primary Dealers (SPDs) under the Standing Liquidity
Facility (SLF) from ₹10,000 crore to ₹15,000 c
---
Page: 12
After a transient spike in the near term, headline
inflation was expected to moderate. Considering the
major upside risks on account of unexpected weather
events and worsening of geopolitical confl
---

In [ ]:
def bm25_retrieval_metrics(eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    for _, row in eval_df.iterrows():
        docs = bm25_retriever.invoke(row["question"])[:k]
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
        else:
            reciprocal_ranks.append(0.0)
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr

hit_rate_bm25, mrr_bm25 = bm25_retrieval_metrics(eval_df, k=4)
print(f"Hit-rate@4 (BM25 only): {hit_rate_bm25:.2%}")
print(f"MRR (BM25 only): {mrr_bm25:.3f}")

Hit-rate@4 (BM25 only): 83.33%
MRR (BM25 only): 0.692

In [ ]:
bm25_retriever_wide = BM25Retriever.from_documents(chunks)
bm25_retriever_wide.k = 15  # wider pool for re-ranker to work with

def bm25_retrieve_and_rerank(query, k=4):
    candidates = bm25_retriever_wide.invoke(query)
    pairs = [[query, doc.page_content] for doc in candidates]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(candidates, scores), key=lambda x: x[1], reverse=True)
    return [doc for doc, score in ranked[:k]]

print("BM25 + Re-ranked retriever ready")

BM25 + Re-ranked retriever ready

In [ ]:
def bm25_reranked_metrics(eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    for _, row in eval_df.iterrows():
        docs = bm25_retrieve_and_rerank(row["question"], k=k)
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
        else:
            reciprocal_ranks.append(0.0)
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr

hit_rate_bm25_rerank, mrr_bm25_rerank = bm25_reranked_metrics(eval_df, k=4)
print(f"Hit-rate@4 (BM25 + Re-ranked): {hit_rate_bm25_rerank:.2%}")
print(f"MRR (BM25 + Re-ranked): {mrr_bm25_rerank:.3f}")

Hit-rate@4 (BM25 + Re-ranked): 86.67%
MRR (BM25 + Re-ranked): 0.767

In [ ]:
def hybrid_retrieve(query, k=4, rrf_k=60):
    # Get ranked results from both retrievers
    bm25_docs = bm25_retriever.invoke(query)
    dense_docs = vectordb.as_retriever(search_kwargs={"k": 10}).invoke(query)

    # Score each unique chunk using Reciprocal Rank Fusion
    scores = {}
    doc_lookup = {}

    for rank, doc in enumerate(bm25_docs):
        key = doc.page_content  # use content as unique identifier
        scores[key] = scores.get(key, 0) + 1 / (rrf_k + rank + 1)
        doc_lookup[key] = doc

    for rank, doc in enumerate(dense_docs):
        key = doc.page_content
        scores[key] = scores.get(key, 0) + 1 / (rrf_k + rank + 1)
        doc_lookup[key] = doc

    # Sort by combined RRF score, descending
    ranked_keys = sorted(scores.keys(), key=lambda k: scores[k], reverse=True)
    return [doc_lookup[key] for key in ranked_keys[:k]]

print("Custom hybrid RRF retriever ready")

Custom hybrid RRF retriever ready

In [ ]:
docs = hybrid_retrieve("What was the repo rate as of April 2025?")
for d in docs:
    print("Page:", d.metadata.get("page") + 1)
    print(d.page_content[:200])
    print("---")

Page: 16
6
Monetary Policy Report April 2025
Box I.1: What Affects Inflation Expectations of Economic Agents?
Anchoring inflation expectations is paramount in
monetary policy formulation, particularly in an i
---
Page: 18
Repo rate (end-period) 6.25 5.75 -
Yield on 91-days treasury bills (end-period) 6.5 6.0 6.4
Yield on 10-year central government
securities (end-period) 6.6 6.4 6.5
Overall balance of payments (US$ bi
---
Page: 75
During H2:2024-25, the WACR, which remained
within the policy corridor and hovered close to the
policy repo rate during October-November, hardened,
moving close to and occasionally breaching the ce
---
Page: 76
8.0
8.5
9.0
1-Apr-24
20-Apr-24
9-May-24
28-May-24
16-Jun-24
5-Jul-24
24-Jul-24
12-Aug-24
31-Aug-24
19-Sep-24
8-Oct-24
27-Oct-24
15-Nov-24
4-Dec-24
23-Dec-24
11-Jan-25
30-Jan-25
18-Feb-25
9-Mar-25
28-M
---

In [ ]:
def hybrid_retrieval_metrics(eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    details = []
    for _, row in eval_df.iterrows():
        docs = hybrid_retrieve(row["question"], k=k)
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
            status = f"HIT (rank {rank})"
        else:
            reciprocal_ranks.append(0.0)
            status = "MISS"
        details.append({"question": row["question"], "ground_truth_page": gt_page,
                         "retrieved_pages": pages, "status": status})
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr, pd.DataFrame(details)

hit_rate_hybrid, mrr_hybrid, details_hybrid_df = hybrid_retrieval_metrics(eval_df, k=4)
print(f"Hit-rate@4 (Hybrid RRF): {hit_rate_hybrid:.2%}")
print(f"MRR (Hybrid RRF): {mrr_hybrid:.3f}")

Hit-rate@4 (Hybrid RRF): 86.67%
MRR (Hybrid RRF): 0.786

In [ ]:
bm25_retriever_wide = BM25Retriever.from_documents(chunks)
bm25_retriever_wide.k = 15

In [ ]:
def hybrid_retrieve_and_rerank(query, k=4, initial_pool=15, rrf_k=60):
    # Get a wider candidate pool from both retrievers before re-ranking
    bm25_docs = BM25Retriever.from_documents(chunks, k=initial_pool).invoke(query)
    dense_docs = vectordb.as_retriever(search_kwargs={"k": initial_pool}).invoke(query)

    # RRF fusion to build one merged candidate list
    scores = {}
    doc_lookup = {}
    for rank, doc in enumerate(bm25_docs):
        key = doc.page_content
        scores[key] = scores.get(key, 0) + 1 / (rrf_k + rank + 1)
        doc_lookup[key] = doc
    for rank, doc in enumerate(dense_docs):
        key = doc.page_content
        scores[key] = scores.get(key, 0) + 1 / (rrf_k + rank + 1)
        doc_lookup[key] = doc

    ranked_keys = sorted(scores.keys(), key=lambda k: scores[k], reverse=True)
    candidates = [doc_lookup[key] for key in ranked_keys[:initial_pool]]

    # Cross-encoder re-ranks the RRF-fused candidate pool
    pairs = [[query, doc.page_content] for doc in candidates]
    ce_scores = reranker.predict(pairs)
    reranked = sorted(zip(candidates, ce_scores), key=lambda x: x[1], reverse=True)
    return [doc for doc, score in reranked[:k]]

print("Hybrid + Re-ranked retriever ready")

Hybrid + Re-ranked retriever ready

In [ ]:
def hybrid_reranked_metrics(eval_df, k=4):
    hits = 0
    reciprocal_ranks = []
    for _, row in eval_df.iterrows():
        docs = hybrid_retrieve_and_rerank(row["question"], k=k)
        pages = [d.metadata.get("page") + 1 for d in docs]
        gt_page = int(row["ground_truth_page"])
        if gt_page in pages:
            hits += 1
            rank = pages.index(gt_page) + 1
            reciprocal_ranks.append(1.0 / rank)
        else:
            reciprocal_ranks.append(0.0)
    hit_rate = hits / len(eval_df)
    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    return hit_rate, mrr

hit_rate_hybrid_rerank, mrr_hybrid_rerank = hybrid_reranked_metrics(eval_df, k=4)
print(f"Hit-rate@4 (Hybrid + Re-ranked): {hit_rate_hybrid_rerank:.2%}")
print(f"MRR (Hybrid + Re-ranked): {mrr_hybrid_rerank:.3f}")

Hit-rate@4 (Hybrid + Re-ranked): 93.33%
MRR (Hybrid + Re-ranked): 0.822

In [ ]:
!pip install -q deepeval

from deepeval.models.base_model import DeepEvalBaseLLM
from deepeval.metrics import GEval, ContextualRelevancyMetric, ContextualRecallMetric
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
import time

class GroqJudge(DeepEvalBaseLLM):
    def __init__(self, model_name="llama-3.1-8b-instant"):
        self.model = ChatGroq(model=model_name, temperature=0)
    def load_model(self):
        return self.model
    def generate(self, prompt: str) -> str:
        return self.model.invoke(prompt).content
    async def a_generate(self, prompt: str) -> str:
        result = await self.model.ainvoke(prompt)
        return result.content
    def get_model_name(self):
        return "Groq-Judge"

judge = GroqJudge()

correctness = GEval(
    name="Correctness",
    criteria="Determine if the actual output is factually consistent with the expected output.",
    evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT, LLMTestCaseParams.EXPECTED_OUTPUT],
    model=judge, threshold=0.5,
)
relevancy = ContextualRelevancyMetric(model=judge, threshold=0.5)
recall = ContextualRecallMetric(model=judge, threshold=0.5)
print("Judge and metrics ready")

Judge and metrics ready

/tmp/ipykernel_1081/3374199413.py:5: DeprecationWarning: 'LLMTestCaseParams' is deprecated and will be removed in a future release. Use 'SingleTurnParams' instead.
  from deepeval.test_case import LLMTestCase, LLMTestCaseParams

In [ ]:
def measure_with_retry(metric, tc, max_retries=5):
    for attempt in range(max_retries):
        try:
            metric.measure(tc)
            return True
        except Exception as e:
            err = str(e).lower()
            if "rate_limit" in err or "429" in err:
                wait = 20 * (attempt + 1)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
            elif "json" in err or "invalid" in err:
                print(f"  Bad JSON from judge, retrying (attempt {attempt+1})...")
                time.sleep(5)
            else:
                raise e
    return False

# Build test cases (uses re-ranked retrieval)
test_cases = []
for _, row in eval_df.iterrows():
    docs = retrieve_and_rerank(row["question"], initial_k=15, final_k=4)
    context = "\n\n".join(d.page_content for d in docs)
    messages = prompt.format_messages(context=context, question=row["question"])
    response = llm.invoke(messages)
    test_cases.append(LLMTestCase(
        input=row["question"],
        actual_output=response.content,
        expected_output=row["expected_answer_summary"],
        retrieval_context=[d.page_content for d in docs],
    ))
    time.sleep(3)

print(f"{len(test_cases)} test cases built")

30 test cases built

In [ ]:
import os
results_list = []
checkpoint_path = "eval_results_checkpoint_rbi.csv"

if os.path.exists(checkpoint_path):
    results_df = pd.read_csv(checkpoint_path)
    results_list = results_df.to_dict("records")
    done_questions = set(results_df["question"])
else:
    done_questions = set()

for i, tc in enumerate(test_cases):
    if tc.input in done_questions:
        continue
    print(f"Scoring test case {i+1}/{len(test_cases)}...")
    measure_with_retry(correctness, tc); time.sleep(8)
    measure_with_retry(relevancy, tc); time.sleep(8)
    measure_with_retry(recall, tc); time.sleep(8)
    results_list.append({
        "question": tc.input,
        "correctness": correctness.score,
        "relevancy": relevancy.score,
        "recall": recall.score,
    })
    pd.DataFrame(results_list).to_csv(checkpoint_path, index=False)

results_df = pd.DataFrame(results_list)
print(results_df)
print()
print("Average Correctness:", results_df["correctness"].mean())
print("Average Contextual Relevancy:", results_df["relevancy"].mean())
print("Average Contextual Recall:", results_df["recall"].mean())

Scoring test case 1/30...

Output()

Output()

Output()

Output()

Scoring test case 2/30...

Output()

  Rate limited, waiting 20s...

Output()

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 3/30...

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Rate limited, waiting 80s...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 4/30...

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Rate limited, waiting 40s...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Rate limited, waiting 80s...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Output()

Scoring test case 5/30...

Output()

Output()

Output()

Scoring test case 6/30...

Output()

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 7/30...

Output()

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 8/30...

Output()

  Rate limited, waiting 20s...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Rate limited, waiting 100s...

Output()

Output()

Scoring test case 9/30...

Output()

Output()

Output()

Scoring test case 10/30...

Output()

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Bad JSON from judge, retrying (attempt 4)...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 11/30...

Output()

Output()

  Bad JSON from judge, retrying (attempt 1)...

Output()

  Bad JSON from judge, retrying (attempt 2)...

Output()

  Bad JSON from judge, retrying (attempt 3)...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 12/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 13/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 14/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 15/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 16/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 17/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 18/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 19/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 20/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Bad JSON from judge, retrying (attempt 5)...

Output()

Scoring test case 21/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 22/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 23/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 24/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 25/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 26/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 27/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 28/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 29/30...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

Scoring test case 30/30...

  Rate limited, waiting 20s...

Output()

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...

Output()

  Rate limited, waiting 20s...

Output()

  Rate limited, waiting 40s...

Output()

  Rate limited, waiting 60s...

Output()

  Rate limited, waiting 80s...

Output()

  Rate limited, waiting 100s...
                                                       question  correctness  \
0   What was India's real GDP growth for 2024-25 per the sec...          0.2
1   By how much was the Cash Reserve Ratio (CRR) reduced in ...          0.8
2         What did the MPC decide at its February 2025 meeting?          0.6
3   What model is used in Box I.1 to study inflation expecta...          0.8
4   What did professional forecasters project for CPI inflat...          0.0
5             What is the CPI inflation projection for 2025-26?          0.0
6           What is the real GDP growth projection for 2025-26?          0.9
7   Where did headline CPI inflation stand relative to the t...          0.9
8   How much did headline inflation surge from August to Sep...          0.2
9                     What was food inflation in February 2025?          0.8
10  How did cereals inflation move from October 2024 to Febr...          0.9
11  What mainly drove the pick-up in core inflation between ...          0.8
12  What was PFCE growth in Q3:2024-25 and its contribution ...          0.9
13  How much did domestic air passenger traffic grow in Q3:2...          0.2
14                 What was India's investment rate in 2023-24?          0.0
15   What were the Centre's gross market borrowings in 2024-25?          0.9
16  What was foodgrains production per the second advance es...          0.2
17              What was rice procurement as of March 31, 2025?          0.8
18  How did industrial sector growth move in 2024-25 per the...          0.9
19  What were the major drivers of liquidity during H2:2024-25?          0.8
20  What was the average daily net absorption under the LAF ...          0.7
21     What was Reserve Money (RM) growth as of March 28, 2025?          0.2
22  What range did the 10-year G-sec yield move in during H2...          0.9
23  What was the weighted average maturity of outstanding G-...          0.2
24          How much did credit to MSMEs grow in February 2025?          0.8
25  By how much did the 1-year median MCLR rise during the M...          0.2
26      How did Euro area and UK GDP growth compare in Q4:2024?          0.9
27                 How did Brazil's GDP growth move in Q4:2024?          0.8
28             What milestone did gold prices cross in Q1:2025?          0.2
29  How did Russia's CPI inflation move between September 20...          0.9

    relevancy    recall
0    0.416667  0.333333
1    0.166667  0.333333
2    0.166667  0.333333
3    0.166667  0.800000
4    0.243902  0.521739
5    0.135135  0.521739
6    0.187500  0.521739
7    0.187500  0.500000
8    0.312500  1.000000
9    0.470588  1.000000
10   0.296875  1.000000
11   0.296875  0.750000
12   0.296875  0.750000
13   0.296875  1.000000
14   0.296875  1.000000
15   0.296875  1.000000
16   0.296875  1.000000
17   0.296875  1.000000
18   0.296875  1.000000
19   0.296875  1.000000
20   0.296875  0.818182
21   0.296875  0.818182
22   0.296875  0.833333
23   0.296875  0.833333
24   0.296875  0.833333
25   0.296875  0.833333
26   0.296875  0.833333
27   0.296875  0.833333
28   0.296875  0.823529
29   0.296875  0.600000

Average Correctness: 0.58
Average Contextual Relevancy: 0.2797097492040103
Average Contextual Recall: 0.7808370146477563